name: PotionRestrict
author: Marcin (CTRL) Wieczorek
version: 1.1
main: co.marcin.potionrestrict.PotionRestrict
commands:
 potionrestrict:
  aliases: [ pr ]
  description: PotionRestrict command

permissions:
 potionrestrict.get:
  default: op
 potionrestrict.set:
  default: op
 potionrestrict.reload:
  default: op
 potionrestrict.bypass:
  default: op
